project:
  type: website
  output-dir: docs


website:
  title: "informatics.legal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - about.qmd 
  google-analytics: "G-0BZLRDQ9RH"
        
format:
  html:
    theme: united
    css: styles.css



